<?xml version="1.0"?>
<robot name="macroed" xmlns:xacro="http://ros.org/wiki/xacro">

 <!-- Unit in this file is determine in meter and kilogram -->

<!-- ###########################################################set up property #################################################################-->
  <xacro:property name="base_width" value="0.156" />
  <xacro:property name="base_length" value="0.118"/>
  <xacro:property name="base_height" value="0.0464"/>
  <xacro:property name="base_height_pos" value="1"/>

  <xacro:property name="right_hip_width" value="0.026"/>
  <xacro:property name="right_hip_length" value="0.048"/>
  <xacro:property name="right_hip_height" value="0.002"/>

  <xacro:property name="foot_width" value="0.09"/>
  <xacro:property name="foot_length" value="0.165"/>
  <xacro:property name="foot_height" value="0.027"/>

  <xacro:property name="upper_foot_width" value="0.026"/>
  <xacro:property name="upper_foot_length" value="0.054"/>
  <xacro:property name="upper_foot_height" value="0.029"/>

  <xacro:property name="right_bum_width" value="0.048"/>
  <xacro:property name="right_bum_length" value="0.0922"/>
  <xacro:property name="right_bum_height" value="0.06"/>

  <xacro:property name="upper_leg_width" value="0.054"/>
  <xacro:property name="upper_leg_length" value="0.03"/>
  <xacro:property name="upper_leg_height" value="0.1553"/>

  <xacro:property name="lower_leg_width" value="0.054"/>
  <xacro:property name="lower_leg_length" value="0.03"/>
  <xacro:property name="lower_leg_height" value="0.16039"/>

  <xacro:property name="ankel_width" value="0.048"/>
  <xacro:property name="ankel_length" value="0.0922"/>
  <xacro:property name="ankel_height" value="0.06"/>

  <xacro:property name="foot_width" value="0.09"/>
  <xacro:property name="foot_length" value="0.165"/>
  <xacro:property name="foot_height" value="0.027"/>

  <xacro:property name="pi" value="3.1415"/>
<!-- ###########################################################set up property #################################################################-->

<!-- ###########################################################set up material #################################################################-->
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="red">
  <color rgba="1 0 0 1"/>
  </material>

  <material name="yellow">
  <color rgba="1 1 0 1"/>
  </material>

  <material name="turqouise">
  <color rgba="0 1 1 1"/>
  </material>

  <material name="violet">
  <color rgba="1 0 1 1"/>
  </material>
<!-- ###########################################################set up material #################################################################-->

  <xacro:macro name="base_inertial" params="mass">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>
<!-- add foot_print -->
  <!-- <link name="foot_print">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
    </visual>
  </link> -->
<!-- add foot_print -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:base_inertial mass="0.291"/>
  </link>

  <!-- ############################################################## macro robot's hip ####################################################-->

  <xacro:macro name="hip" params='prefix reflect member parent z_origin'>
    <link name="${prefix}_${member}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${right_hip_width} ${right_hip_length} ${right_hip_height}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${right_hip_width} ${right_hip_length} ${right_hip_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${parent}_to_${prefix}_${member}_link" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="${prefix}_${member}_link"/>
      <origin xyz="${0.054*reflect} 0 ${z_origin}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  <xacro:hip prefix="right" reflect="1" member="hip" parent="base_link" z_origin="${-(base_height+right_hip_height)/2}"/>
  <xacro:hip prefix="left" reflect="-1" member="hip" parent="base_link" z_origin="${-(base_height+right_hip_height)/2}"/>

  <xacro:hip prefix="right" reflect="0" member="upper_foot" parent="right_ankel_link" z_origin="${-ankel_height/2}"/>
  <xacro:hip prefix="left" reflect="0" member="upper_foot" parent="left_ankel_link" z_origin="${-ankel_height/2}"/>


  <!-- ############################################################## macro robot's bum ####################################################-->
  <xacro:macro name="bum" params="prefix member parent z_origin">
    <link name="${prefix}_${member}_link">
      <visual>
        <origin xyz="0 -0.0221 0"/>
        <geometry>
          <box size="${right_bum_width} ${right_bum_length} ${right_bum_height}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <box size="${right_bum_width} ${right_bum_length} ${right_bum_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_${parent}_to_${prefix}_${member}" type="fixed">
      <parent link="${prefix}_${parent}_link"/>
      <child link="${prefix}_${member}_link"/>
      <origin xyz="0 0 ${z_origin}"/>
    </joint>
      <!-- origin may been wong because 'z' may be not bum height divine by 2, it might increse in 'z' axis -->
  </xacro:macro>
  <!-- right hip link to right bum link-->
  <xacro:bum prefix="right" member="bum" parent="hip" z_origin="${-right_bum_height/2}"/>   
  <!-- left hip link to left bum link -->
  <xacro:bum prefix="left" member="bum" parent="hip" z_origin="${-right_bum_height/2}"/>
  <!-- right ankel link to right lower leg-->
  <xacro:bum prefix="right" member="ankel" parent="lower_leg" z_origin="${-lower_leg_height}"/>
  <!-- left ankel link to left lower leg -->
  <xacro:bum prefix="left" member="ankel" parent="lower_leg" z_origin="${-lower_leg_height}"/> 
  

  <!--########################################################## macro robot's upper leg #######################################################-->
  <xacro:macro name="upper_leg" params="prefix">
    <link name="${prefix}_upper_leg_link">
      <visual>
        <origin xyz="0 0 ${-upper_leg_height/2}"/>
        <geometry>
          <box size="${upper_leg_width} ${upper_leg_length} ${upper_leg_height}"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <geometry>
          <box size="${upper_leg_width} ${upper_leg_length} ${upper_leg_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_bum_to_${prefix}_upper_leg" type="fixed">
      <parent link="${prefix}_bum_link"/>
      <child link="${prefix}_upper_leg_link"/>
      <origin xyz="0 0 0"/>
      <!-- origin must be the same with bum joint -->
    </joint>

  </xacro:macro>
  <xacro:upper_leg prefix="right"/>
  <xacro:upper_leg prefix="left"/>

  <!--########################################################## macro robot's lower leg #######################################################-->

  <xacro:macro name="lower_leg" params="prefix">
    <link name="${prefix}_lower_leg_link">
      <visual>
        <origin xyz="0 0 ${-lower_leg_height/2}"/>
        <geometry>
          <box size="${lower_leg_width} ${lower_leg_length} ${lower_leg_height}"/>
        </geometry>
        <material name="yellow"/>
      </visual>
      <collision>
        <geometry>
          <box size="${lower_leg_width} ${lower_leg_length} ${lower_leg_height}"/>
        </geometry>
      </collision>
    </link>

  <joint name="${prefix}_upper_leg_to_${prefix}_lower_leg" type="fixed">
    <parent link="${prefix}_upper_leg_link"/>
    <child link="${prefix}_lower_leg_link"/>
    <origin xyz="0 0 ${-upper_leg_height}"/>
  </joint>
  </xacro:macro>
  <xacro:lower_leg prefix="right"/>
  <xacro:lower_leg prefix="left"/>

  <!--########################################################## macro robot's foot #######################################################-->

  <xacro:macro name="foot" params="prefix reflect">
    <link name="${prefix}_foot_link">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <box size="${foot_width} ${foot_length} ${foot_height}"/>
        </geometry>
        <material name="turqouise"/>
      </visual>
      <collision>
        <geometry>
          <box size="${foot_width} ${foot_length} ${foot_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_upper_foot_to_${prefix}_foot" type="fixed">
      <parent link="${prefix}_upper_foot_link"/>
      <child link="${prefix}_foot_link"/>
      <origin xyz="${0.018*reflect} -0.00989 0"/>
    </joint>
  </xacro:macro>
  <xacro:foot prefix="right" reflect="1"/>
  <xacro:foot prefix="left" reflect="-1"/>

</robot>

  <!--########################################################## macro robot's upper foot #######################################################-->




